FABRICANTES = ["MICROSOFT", "AZURE", "OFFICE 365", "ORACLE", "AMAZON WEB SERVICES",
               "AWS", "GOOGLE", "GCP", "UNIFIED"]
DIRECTAS = ["NUBE", "CLOUD", "SOFTWARE"]
CONDICIONADAS = ["LICENCI", "SUSCRIPCI"]
UNSPSC_TIC = ["V1.43", "V1.8111", "V1.8116"]